baseURL = "https://thelowcodebuilder.com/"
languageCode = "en-us"
title = "The Low Code Builder"
theme = "PaperMod"
paginate = 10

[outputs]
home = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]